// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE4Tm607uwr1GoiyK8Mlahpju0wl3ADcI',
    appId: '1:349750063232:web:e8a77320ab6b818730b665',
    messagingSenderId: '349750063232',
    projectId: 'todolist0-5752e',
    authDomain: 'todolist0-5752e.firebaseapp.com',
    storageBucket: 'todolist0-5752e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0BjkwTVpFbeuNde2PAaiQSGx5TSF3gJA',
    appId: '1:349750063232:android:30d091a1a946ae4130b665',
    messagingSenderId: '349750063232',
    projectId: 'todolist0-5752e',
    storageBucket: 'todolist0-5752e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3iwTEb2gEHSubc2vZL3nsyqXDElAzSfE',
    appId: '1:349750063232:ios:a2aaa3880734a88930b665',
    messagingSenderId: '349750063232',
    projectId: 'todolist0-5752e',
    storageBucket: 'todolist0-5752e.firebasestorage.app',
    iosBundleId: 'com.example.todoapp0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3iwTEb2gEHSubc2vZL3nsyqXDElAzSfE',
    appId: '1:349750063232:ios:a2aaa3880734a88930b665',
    messagingSenderId: '349750063232',
    projectId: 'todolist0-5752e',
    storageBucket: 'todolist0-5752e.firebasestorage.app',
    iosBundleId: 'com.example.todoapp0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE4Tm607uwr1GoiyK8Mlahpju0wl3ADcI',
    appId: '1:349750063232:web:8e281233140ddcb930b665',
    messagingSenderId: '349750063232',
    projectId: 'todolist0-5752e',
    authDomain: 'todolist0-5752e.firebaseapp.com',
    storageBucket: 'todolist0-5752e.firebasestorage.app',
  );
}
